import { resolvePresentationColor, presentationTextStyle } from '@/theme/presentation';
import { Image } from 'expo-image';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Pressable, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useProfileTheme } from '@/features/profile/theme';
import { momentsApi } from './api';
import type { Moment } from './types';
export function MomentDrafts() {
  const theme = useProfileTheme(); const [items, setItems] = useState<Moment[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const request = useRef<AbortController | null>(null);
  const load = useCallback(async () => { request.current?.abort(); const controller = new AbortController(); request.current = controller; setLoading(true); setError(null); try { const rows = await momentsApi.drafts(controller.signal); if (!controller.signal.aborted) setItems(rows); } catch (failure) { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : 'Could not load drafts'); } finally { if (!controller.signal.aborted) setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); return () => request.current?.abort(); }, [load]));
  const discard = (item: Moment) => Alert.alert('Discard unfinished Moment?', 'Any uploaded video and cover will be removed.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Discard', style: 'destructive', onPress: () => { setBusy(item.id); void momentsApi.delete(item.id).then(() => load()).catch(failure => setError(failure.message)).finally(() => setBusy(null)); } }]);
  return <SafeAreaView style={{ flex: 1, backgroundColor: resolvePresentationColor(theme.canvas, 'backgroundColor', 'content') }}><FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={{ padding: 24, gap: 24 }}
    ListHeaderComponent={<View style={{ gap: 24 }}><Pressable onPress={() => router.back()}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.accent, 'color', 'content') })}>‹ Back</Text></Pressable><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontSize: 28, fontWeight: '600' })}>Unfinished Moments</Text>{error ? <Pressable onPress={() => void load()}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.danger, 'color', 'content') })}>{error} · Retry</Text></Pressable> : null}</View>}
    ListEmptyComponent={loading ? <ActivityIndicator color={resolvePresentationColor(theme.muted, 'color', 'content')} /> : <Text style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content'), paddingVertical: 30 })}>You’re all caught up. Your shared Moments live on your profile.</Text>}
    renderItem={({ item }) => <View style={{ flexDirection: 'row', gap: 16 }}><Image source={item.cover_url} style={{ width: 72, height: 108, borderRadius: 14, backgroundColor: resolvePresentationColor(theme.placeholder, 'backgroundColor', 'content') }} contentFit="cover" /><View style={{ flex: 1, gap: 10 }}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontSize: 17, fontWeight: '600' })}>{item.place.name}</Text><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content') })}>{item.status === 'ready' ? 'Video is ready to share.' : item.status === 'deleting' ? 'Cleanup needs another try.' : 'Choose your video again to finish.'}</Text><View style={{ flexDirection: 'row', gap: 22 }}>{item.status !== 'deleting' ? <Pressable disabled={Boolean(busy)} onPress={() => router.push({ pathname: '/moment/new', params: { draftId: item.id } })}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.accent, 'color', 'content') })}>Continue</Text></Pressable> : null}<Pressable disabled={Boolean(busy)} onPress={() => discard(item)}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.danger, 'color', 'content') })}>{busy === item.id ? 'Removing…' : 'Discard'}</Text></Pressable></View></View></View>} />
  </SafeAreaView>;
}
