import { usePresentationStyles, resolvePresentationColor, presentationTextStyle } from '@/theme/presentation';
import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import MapView, { Marker } from 'react-native-maps';
import { postMediaShape } from '@/features/posts/mediaShape';
import { postTarget } from '@/features/posts/data';
import { ProfileAvatarImage } from '@/features/profile/components/ProfileAvatarImage';
import type { ProfileTheme } from '@/features/profile/theme';
import { spacing } from '@/theme/spacing';
import { bookedVia, stayPoint, type Stay, type StayPoint, type StayTip } from './api';
import { BookingChip, StayMetadata, stayContext } from './StayCard';
import { StayGallery } from './StayGallery';
import { GlassButton } from './StayGlass';
import { Action, Sheet } from './StayUI';
export function StayDetail({ stay, theme, loading, error, onClose, onRetry, onMore, onMenu, onMap }: { stay: Stay; theme: ProfileTheme; loading: boolean; error?: string; onClose: () => void; onRetry: () => void; onMore: () => void; onMenu?: (tip: StayTip) => void; onMap: (point: StayPoint) => void }) {
  const styles = usePresentationStyles(presentationBaselineStyles);

  const point = stayPoint(stay), owner = onMenu ? stay.tips.find(tip => tip.own) : undefined, hasPhotos = Boolean(stay.photos?.length);
  const map = () => { if (point) { onClose(); onMap(point); } };
  const profile = (tip: StayTip) => { onClose(); router.push({ pathname: '/public-profile/[id]', params: { id: tip.creator.id } }); };
  const journey = (tip: StayTip) => { onClose(); router.push(postTarget(tip.journey.id, tip.own)); };
  return <Sheet title="Stay" closeLabel="Back" theme={theme} onClose={onClose}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    {hasPhotos ? <StayGallery photos={stay.photos} fallbackUrl={stay.cover_url} city={stay.city} theme={theme} postCorners countInteractive onRetry={onRetry} onMenu={owner ? () => onMenu!(owner) : undefined} /> : owner ? <View style={{ alignItems: 'flex-end' }}><GlassButton label="Stay options" theme={theme} onPress={() => onMenu!(owner)} style={{ width: 36, height: 36, alignItems: 'center', justifyContent: 'center' }}><Ionicons name="ellipsis-horizontal" size={20} color={resolvePresentationColor(theme.ink, 'color', 'content')} /></GlassButton></View> : null}
    <View style={[styles.identity, !hasPhotos && { marginTop: owner ? spacing.xxs : 0 }]}><Text style={presentationTextStyle([styles.title, { color: resolvePresentationColor(theme.ink, 'color', 'content') }])}>{stay.name}</Text><View style={{ marginTop: spacing.xxs }}><StayMetadata stay={stay} theme={theme} /></View>{bookedVia(stay.booking_source) ? <View style={styles.booking}><BookingChip source={stay.booking_source} theme={theme} /></View> : null}</View>
    {stay.tips.map((tip, index) => <View key={tip.id} style={styles.recommendation}>
      {tip.tip ? <><Text style={presentationTextStyle([styles.heading, { color: resolvePresentationColor(theme.ink, 'color', 'content') }])}>{stay.tips.length > 1 ? 'Traveler recommendations' : 'Traveler recommendation'}</Text><Text style={presentationTextStyle([styles.quote, { color: resolvePresentationColor(theme.ink, 'color', 'content') }])}>“{tip.tip}”</Text></> : null}
      {index > 0 && (bookedVia(tip.booking_source) || tip.photos?.length) ? <View style={{ marginTop: spacing.md }}><BookingChip source={tip.booking_source} theme={theme} />{tip.photos?.length ? <View style={{ marginTop: spacing.md }}><StayGallery photos={tip.photos} theme={theme} postCorners countInteractive onRetry={onRetry} onMenu={tip.own && onMenu ? () => onMenu(tip) : undefined} /></View> : null}</View> : null}
      <View style={[styles.creatorRow, { marginTop: tip.tip ? spacing.lg : 0 }]}><Pressable accessibilityRole="button" accessibilityLabel={`View ${tip.creator.display_name}'s profile`} onPress={() => profile(tip)} style={styles.creator}><ProfileAvatarImage source={tip.creator.avatar_url} label={tip.creator.display_name} cacheKey={`stay-avatar:${tip.creator.id}`} fallbackIconSize={18} style={styles.avatar} /><View style={{ flex: 1 }}><Text numberOfLines={2} style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontSize: 15, fontWeight: '600' })}>{tip.creator.display_name}</Text><Text numberOfLines={2} style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content'), fontSize: 12, marginTop: 4 })}>{stayContext(tip)}</Text></View></Pressable><GlassButton label="View journey" theme={theme} accent onPress={() => journey(tip)} style={styles.glassAction}><Ionicons name="map-outline" size={14} color={resolvePresentationColor(theme.accent, 'color', 'content')} /><Text style={presentationTextStyle([styles.actionText, { color: resolvePresentationColor(theme.accent, 'color', 'content') }])}>View journey</Text><Ionicons name="chevron-forward" size={11} color={resolvePresentationColor(theme.accent, 'color', 'content')} /></GlassButton></View>
    </View>)}
    {point ? <View style={styles.location}><View style={[styles.separator, { backgroundColor: resolvePresentationColor(theme.divider, 'backgroundColor', 'content') }]} /><Text style={presentationTextStyle([styles.heading, { color: resolvePresentationColor(theme.ink, 'color', 'content'), marginTop: spacing.xl }])}>Location</Text><Pressable accessibilityRole="button" accessibilityLabel="Open Stay location on map" onPress={map} style={[styles.map, { backgroundColor: resolvePresentationColor(theme.placeholder, 'backgroundColor', 'control') }]}><MapView pointerEvents="none" key={`${point.id}:${point.latitude}:${point.longitude}`} style={StyleSheet.absoluteFill} initialRegion={{ ...point, latitudeDelta: stay.manual ? .15 : .025, longitudeDelta: stay.manual ? .15 : .025 }} userInterfaceStyle={theme.dark ? 'dark' : 'light'} scrollEnabled={false} zoomEnabled={false} rotateEnabled={false} pitchEnabled={false} showsUserLocation={false} showsCompass={false} toolbarEnabled={false}><Marker coordinate={point} title={stay.manual ? 'City location' : stay.name} /></MapView></Pressable>{stay.manual ? <View style={styles.privacy}><Ionicons name="information-circle-outline" size={14} color={resolvePresentationColor(theme.muted, 'color', 'content')} /><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content'), fontSize: 12, lineHeight: 18, flex: 1 })}>City location only · No private address shared</Text></View> : null}<GlassButton label="View on map" theme={theme} accent onPress={map} style={[styles.glassAction, styles.mapAction]}><Ionicons name="map-outline" size={14} color={resolvePresentationColor(theme.accent, 'color', 'content')} /><Text style={presentationTextStyle([styles.actionText, { color: resolvePresentationColor(theme.accent, 'color', 'content') }])}>View on map</Text><Ionicons name="chevron-forward" size={11} color={resolvePresentationColor(theme.accent, 'color', 'content')} /></GlassButton></View> : null}
    {loading ? <ActivityIndicator accessibilityLabel="Loading Stay detail" color={resolvePresentationColor(theme.muted, 'color', 'content')} style={{ marginTop: spacing.lg }} /> : null}
    {error ? <View style={{ marginTop: spacing.lg }}><Text accessibilityRole="alert" style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content') })}>{error}</Text><Action label="Retry" theme={theme} onPress={onRetry} /></View> : null}
    {stay.next_offset != null ? <Action label="More traveler tips" theme={theme} disabled={loading} onPress={onMore} /> : null}
  </ScrollView></Sheet>;
}
const styles = StyleSheet.create({ content: { paddingHorizontal: spacing.screen, paddingTop: spacing.lg, paddingBottom: spacing.xl }, identity: { marginTop: spacing.lg }, title: { fontSize: 24, lineHeight: 30, fontWeight: '600', letterSpacing: -.4 }, heading: { fontSize: 20, lineHeight: 26, fontWeight: '600', letterSpacing: -.3 }, booking: { marginTop: spacing.md }, recommendation: { marginTop: spacing.xl + spacing.xs }, quote: { marginTop: spacing.md + spacing.xxs, fontSize: 17, fontWeight: '400', lineHeight: 27 }, creatorRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: spacing.sm }, creator: { flex: 1, minWidth: 110, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, avatar: { width: 40, height: 40, borderRadius: 20 }, glassAction: { minHeight: 38, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 5, maxWidth: '100%' }, actionText: { fontSize: 12, fontWeight: '600', flexShrink: 1 }, location: { marginTop: spacing.xl }, separator: { height: StyleSheet.hairlineWidth }, map: { ...postMediaShape, height: 176, overflow: 'hidden', marginTop: spacing.md + spacing.xxs }, privacy: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginTop: spacing.sm + spacing.xxs }, mapAction: { alignSelf: 'flex-start', marginTop: spacing.md + spacing.xxs } });
const presentationBaselineStyles = styles;
