import { usePresentationStyles, resolvePresentationColor, presentationTextStyle } from '@/theme/presentation';
import { KeyboardAvoidingView, Modal, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { ProfileTheme } from '@/features/profile/theme';
export function Action({ label, onPress, theme, disabled = false }: { label: string; onPress: () => void; theme: ProfileTheme; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => ({ minHeight: 44, justifyContent: 'center', paddingVertical: 8, opacity: disabled || pressed ? .5 : 1 })}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.accent, 'color', 'content'), fontSize: 15, fontWeight: '600' })}>{label}</Text></Pressable>; }
export function Sheet({ children, title, onClose, theme, closeLabel = 'Done', closeDisabled = false, closeControl }: { children: React.ReactNode; title: string; onClose: () => void; theme: ProfileTheme; closeLabel?: string; closeDisabled?: boolean; closeControl?: React.ReactNode }) {
  const styles = usePresentationStyles(presentationBaselineStyles, 'surface');
 return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={{ flex: 1, backgroundColor: resolvePresentationColor(theme.canvas, 'backgroundColor', 'surface') }} edges={['bottom', 'top']}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={{ alignSelf: 'center', width: 36, height: 4, borderRadius: 2, marginTop: 8, backgroundColor: resolvePresentationColor(theme.divider, 'backgroundColor', 'content') }} /><View style={styles.header}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontSize: 22, fontWeight: '600', flexShrink: 1 })}>{title}</Text>{closeControl ?? <Action label={closeLabel} disabled={closeDisabled} theme={theme} onPress={onClose} />}</View>{children}</KeyboardAvoidingView></SafeAreaView></Modal>; }
const styles = StyleSheet.create({ header: { paddingHorizontal: 22, paddingVertical: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 } });
const presentationBaselineStyles = styles;
