import { usePresentationStyles, resolvePresentationColor, presentationInterfaceStyle, presentationTextStyle } from '@/theme/presentation';
import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useEffect, useMemo, useState, useSyncExternalStore } from 'react';
import { FlatList, Keyboard, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DiscoverJourneyCard } from '@/features/discover/components/DiscoverJourneyCard';
import { FollowButton } from '@/features/follows/FollowButton';
import { ProfileAvatarImage } from '@/features/profile/components/ProfileAvatarImage';
import { useProfileTheme } from '@/features/profile/theme';
import LibrarySearchScreen from '@/features/search/LibrarySearchScreen';
import { recentSearchStorage } from '@/features/search/storage';
import { addRecentSearch } from '@/features/search/utils';
import { exploreApi, type Category, type SearchResults } from './api';
import { DestinationCard, MomentPreviews, SearchSkeleton, StayResults } from './DiscoveryContent';
import { createExploreStore } from './store';
import { ForYouGrid } from './ForYouGrid';
const categories: Category[] = ['places', 'journeys', 'stays', 'users', 'moments'];
const labels = { users: 'Profiles', journeys: 'Journeys', places: 'Places', stays: 'Stays', moments: 'Moments' };
type Row = { key: string; category: Category; index: number };
function rowSpan(category: Category, discovery: boolean) { return category === 'moments' ? 3 : category === 'journeys' || category === 'places' && discovery ? 2 : 1; }
function resultRows(results: SearchResults | null, tab: Category | 'all', discovery: boolean): Row[] {
  if (!results) return [];
  return categories.filter(category => tab === 'all' || category === tab).flatMap(category => Array.from({ length: Math.ceil(results[category].items.length / rowSpan(category, discovery)) }, (_, index) => ({ category, index, key: `${category}:${index}` })));
}
export function ExploreScreen() {
  const styles = usePresentationStyles(presentationBaselineStyles);

  const theme = useProfileTheme();
  const store = useMemo(() => createExploreStore(exploreApi.search), []);
  const search = useSyncExternalStore(store.subscribe, store.getSnapshot, store.getSnapshot);
  const [recent, setRecent] = useState<string[]>([]), [storageError, setStorageError] = useState(false), [library, setLibrary] = useState(false), [focused, setFocused] = useState(false);
  useEffect(() => { let active = true; void recentSearchStorage.get().then(items => { if (active) setRecent(items); }).catch(() => { if (active) setStorageError(true); }); return () => { active = false; }; }, []);
  useFocusEffect(useCallback(() => {
    if (library) return;
    if (store.getSnapshot().category === 'all') void store.resume();
    else void store.refresh();
    return () => store.suspend(store.getSnapshot().category === 'all');
  }, [store, library]));
  function saveRecent(items: string[]) { setRecent(items); setStorageError(false); void recentSearchStorage.set(items).catch(() => setStorageError(true)); }
  const remember = () => { if (search.query.trim().replace(/^@/, '').length >= 2) saveRecent(addRecentSearch(recent, search.query.trim())); };
  const openJourney = (id: string) => { remember(); router.push({ pathname: '/post/[id]', params: { id, scope: 'public' } }); };
  const openPlace = (id: string) => { remember(); router.push(`/explore/place/${id}`); };
  const searching = Boolean(search.query.trim());
  const tab = search.category;
  const rows = resultRows(search.results, tab, !searching);
  if (library) return <View style={{ flex: 1, backgroundColor: resolvePresentationColor(theme.canvas, 'backgroundColor', 'content') }}><SafeAreaView edges={['top']}><Pressable style={styles.link} onPress={() => setLibrary(false)}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content') })}>‹ Search Vialbum</Text></Pressable></SafeAreaView><LibrarySearchScreen /></View>;
  return <SafeAreaView edges={[]} style={{ flex: 1, backgroundColor: resolvePresentationColor(theme.canvas, 'backgroundColor', 'content') }}>
    <View style={styles.heading}><Text style={presentationTextStyle([styles.title, { color: resolvePresentationColor(theme.ink, 'color', 'content') }])}>Search Vialbum</Text><Pressable accessibilityRole="button" accessibilityLabel="Search my library" style={styles.touch} onPress={() => setLibrary(true)}><Ionicons name="book-outline" size={21} color={resolvePresentationColor(theme.muted, 'color', 'content')} /></Pressable></View>
    <View style={[styles.field, { backgroundColor: resolvePresentationColor(theme.elevatedSurface, 'backgroundColor', 'control') }]}><Ionicons name="search" size={20} color={resolvePresentationColor(theme.muted, 'color', 'content')} /><TextInput style={presentationTextStyle([styles.input, { color: resolvePresentationColor(theme.ink, 'color', 'control') }])} value={search.query} onChangeText={store.setQuery} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} maxLength={100} placeholder="Places, journeys, people…" placeholderTextColor={resolvePresentationColor(theme.muted, 'placeholderTextColor', 'control')} accessibilityLabel="Search places, journeys, people" autoCapitalize="none" autoCorrect={false} returnKeyType="search" onSubmitEditing={() => { remember(); Keyboard.dismiss(); void store.refresh(); }} keyboardAppearance={presentationInterfaceStyle()} />{search.query ? <Pressable style={styles.touch} accessibilityLabel="Clear search" accessibilityRole="button" onPress={() => store.setQuery('')}><Ionicons name="close-circle" size={22} color={resolvePresentationColor(theme.muted, 'color', 'content')} /></Pressable> : null}</View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexGrow: 0 }} contentContainerStyle={styles.tabs}>{(['all', ...categories] as const).map(category => <Pressable key={category} accessibilityRole="tab" accessibilityState={{ selected: tab === category }} onPress={() => store.setCategory(category)} style={styles.chipTarget}><View style={[styles.chip, { backgroundColor: resolvePresentationColor(tab === category ? theme.placeholder : 'transparent', 'backgroundColor', 'control'), borderWidth: tab === category ? 0 : 1, borderColor: resolvePresentationColor(theme.border, 'borderColor', 'control') }]}><Text numberOfLines={1} style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontWeight: tab === category ? '600' : '400' })}>{category === 'all' ? 'For you' : labels[category]}</Text></View></Pressable>)}</ScrollView>
    {tab === 'all' ? <ForYouGrid revision={search.revision} results={search.results} loading={search.loading} more={search.more} error={search.error} query={search.query} theme={theme} refresh={store.refresh} loadMore={store.loadMore} onJourney={openJourney} onOpen={remember} /> : <FlatList data={rows} keyExtractor={item => item.key} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={styles.content}
      ListHeaderComponent={<View>{search.loading ? <SearchSkeleton theme={theme} /> : null}{search.error ? <Pressable accessibilityRole="button" accessibilityLabel="Retry discovery" onPress={() => void store.refresh()} style={styles.link}><Text accessibilityRole="alert" style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content') })}>{search.error}</Text><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.accent, 'color', 'content'), marginTop: 8 })}>Retry</Text></Pressable> : null}{storageError ? <Text style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content') })}>Recent searches could not be saved or loaded.</Text> : null}
        {!searching && focused && recent.length ? <View><View style={styles.sectionRow}><Text style={presentationTextStyle([styles.section, { color: resolvePresentationColor(theme.ink, 'color', 'content') }])}>Recent</Text><Pressable style={styles.touch} accessibilityRole="button" accessibilityLabel="Clear recent searches" onPress={() => { setRecent([]); void recentSearchStorage.clear().catch(() => setStorageError(true)); }}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.accent, 'color', 'content') })}>Clear all</Text></Pressable></View>{recent.map(item => <View key={item} style={styles.person}><Pressable accessibilityRole="button" style={styles.identity} onPress={() => store.setQuery(item)}><Ionicons name="time-outline" size={19} color={resolvePresentationColor(theme.muted, 'color', 'content')} /><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), flex: 1 })}>{item}</Text></Pressable><Pressable style={styles.touch} accessibilityRole="button" accessibilityLabel={`Remove ${item}`} onPress={() => saveRecent(recent.filter(value => value !== item))}><Ionicons name="close" size={20} color={resolvePresentationColor(theme.muted, 'color', 'content')} /></Pressable></View>)}</View> : null}
      </View>}
      ListFooterComponent={<Text style={presentationTextStyle({ color: resolvePresentationColor(theme.subtle, 'color', 'content'), fontSize: 11, marginTop: 24 })}>Place data © Geoapify / OpenStreetMap contributors</Text>}
      ListEmptyComponent={!search.loading && !search.error && searching ? <View style={styles.empty}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content') })}>{search.results ? `No results for “${search.query.trim()}”` : 'Type at least two characters.'}</Text><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content'), marginTop: 8 })}>Try another place, journey or traveler.</Text></View> : !searching && !search.loading && !search.error ? <Text style={presentationTextStyle([styles.empty, { color: resolvePresentationColor(theme.muted, 'color', 'content') }])}>{`No public ${labels[tab].toLowerCase()} yet.`}</Text> : null}

      renderItem={({ item: row }) => {
        const results = search.results!, page = results[row.category];
        const last = row.index === Math.ceil(page.items.length / rowSpan(row.category, !searching)) - 1;
        return <View >
          {row.category === 'users' ? (() => { const person = results.users.items[row.index]; return <View style={styles.person}><Pressable accessibilityRole="button" accessibilityLabel={`View ${person.username}'s profile`} style={styles.identity} onPress={() => { remember(); router.push(`/public-profile/${person.id}`); }}><ProfileAvatarImage source={person.avatar_url} label={person.username} cacheKey={`creator:${person.id}`} style={styles.avatar} fallbackIconSize={22} /><View style={styles.flex}><Text numberOfLines={2} style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontWeight: '600' })}>{person.username}</Text><Text numberOfLines={2} style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content') })}>{person.display_name}</Text></View></Pressable><FollowButton id={person.id} initial={person.is_following} compact /></View>; })() : row.category === 'journeys' ? <View style={styles.pair}>{results.journeys.items.slice(row.index * 2, row.index * 2 + 2).map(journey => <View key={journey.id} style={{ width: '50%' }}><DiscoverJourneyCard journey={journey} theme={theme} onOpen={openJourney} /></View>)}</View> : row.category === 'moments' ? <MomentPreviews items={results.moments.items.slice(row.index * 3, row.index * 3 + 3)} theme={theme} /> : row.category === 'stays' ? <StayResults items={[results.stays.items[row.index]]} theme={theme} /> : !searching ? <View style={styles.destinationGrid}>{results.places.items.slice(row.index * 2, row.index * 2 + 2).map(place => <View key={place.id} style={{ width: '48%' }}><DestinationCard place={place} theme={theme} onPress={() => openPlace(place.id)} /></View>)}</View> : (() => { const place = results.places.items[row.index]; return <Pressable accessibilityRole="button" accessibilityLabel={`Explore ${place.name}, ${place.country}`} style={styles.person} onPress={() => openPlace(place.id)}><Ionicons name="location-outline" size={25} color={resolvePresentationColor(theme.muted, 'color', 'content')} /><View style={styles.flex}><Text numberOfLines={2} style={presentationTextStyle({ color: resolvePresentationColor(theme.ink, 'color', 'content'), fontWeight: '600' })}>{place.name}, {place.country}</Text><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.muted, 'color', 'content') })}>{place.locality ? 'City · Destination' : 'Place · Destination'}</Text></View><Ionicons name="chevron-forward" size={18} color={resolvePresentationColor(theme.subtle, 'color', 'content')} /></Pressable>; })()}
          {last && page.next_cursor ? <Pressable accessibilityRole="button" disabled={Boolean(search.more)} style={styles.link} onPress={() => void store.loadMore(row.category)}><Text style={presentationTextStyle({ color: resolvePresentationColor(theme.accent, 'color', 'content') })}>{search.more === row.category ? 'Loading…' : `More ${labels[row.category].toLowerCase()}`}</Text></Pressable> : null}
        </View>;
      }} />}
  </SafeAreaView>;
}
const styles = StyleSheet.create({ heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 22, paddingVertical: 12, gap: 8 }, title: { fontSize: 30, fontWeight: '700', letterSpacing: -.8, flexShrink: 1 }, section: { fontSize: 21, fontWeight: '600', marginVertical: 18 }, sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, touch: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' }, field: { marginHorizontal: 22, borderRadius: 17, paddingHorizontal: 14, minHeight: 54, flexDirection: 'row', gap: 8, alignItems: 'center' }, input: { flex: 1, fontSize: 16, paddingVertical: 14 }, tabs: { paddingHorizontal: 22, gap: 8, paddingTop: 8, paddingBottom: 4 }, chipTarget: { minHeight: 44, justifyContent: 'center', flexShrink: 0 }, chip: { minHeight: 34, paddingHorizontal: 14, paddingVertical: 6, borderRadius: 18, justifyContent: 'center' }, content: { paddingHorizontal: 22, paddingBottom: 40 }, person: { flexDirection: 'row', gap: 12, alignItems: 'center', paddingVertical: 13, minHeight: 58 }, identity: { flex: 1, flexDirection: 'row', gap: 12, alignItems: 'center', minHeight: 44 }, flex: { flex: 1 }, avatar: { width: 46, height: 46, borderRadius: 23 }, pair: { flexDirection: 'row', alignItems: 'flex-start', marginHorizontal: -5 }, destinationGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 14, marginBottom: 14 }, link: { minHeight: 44, padding: 16, alignItems: 'center' }, empty: { paddingVertical: 30, textAlign: 'center', lineHeight: 22 } });
const presentationBaselineStyles = styles;
